#
# Example Bots configuration for the TomlBotsConfigProvider
#

[bots]

  [bots.slack]
    type = "slack"
    enabled = false
    [bots.slack.storage]
      storage = "mongo"
      [bots.slack.storage.config]
        URL = "mongodb://user1:test@localhost/testdb" # URL to connect to
        Database = "testdb" # Database to use
    [bots.slack.config]
      workspace = "something"
	    token = "token_goes_here"

    [bots.slack.plugins.1]
      type = "echo"
      [bots.slack.plugins.1.config]
        onlywhispers = false

    [bots.slack.plugins.2]
      type = "giveaway"
      [bots.slack.plugins.2.config]
        mods = ["user1", "user2"]
        onlymods = true

    [bots.slack.plugins.3]
      type = "httpping"

    [bots.slack.plugins.4]
      type = "roll"

    [bots.slack.plugins.5]
      type = "version"

    [bots.slack.plugins.6]
      type = "vote"
      [bots.slack.plugins.6.config]
        mods = ["user1", "user2"]
        onlymods = true

    [bots.slack.plugins.7]
      type = "quotes"
      [bots.slack.plugins.7.config]
        mods = ["user1", "user2"]
        onlymods = true

  [bots.mm]
    type = "mattermost"
    enabled = false
    [bots.mm.storage]
      storage = "memory"
      [bots.mm.storage.config]
        URL = "mongodb://user1:test@localhost/testdb" # URL to connect to
        Database = "testdb" # Database to use
    [bots.mm.config]
			server = "https://server.com"
			username = "username_goes_here"
			password = "password_goes_here"

    [bots.mm.plugins.1]
      type = "echo"
      [bots.mm.plugins.1.config]
        onlywhispers = false

    [bots.mm.plugins.2]
      type = "httpping"

    [bots.mm.plugins.3]
      type = "roll"
