#
# Example Bots configuration for the TomlBotsConfigProvider
#

[bots]

  [bots.slack]
    type = "slack"
    enabled = false
    [bots.slack.storage]
      storage = "mongo"
      [bots.slack.storage.config]
        URL = "mongodb://user1:test@localhost/testdb" # URL to connect to
        Database = "testdb" # Database to use
    [bots.slack.config]
      workspace = "something"
	    token = "token_goes_here"
    [bots.slack.plugins.1]
      type = "echo"
      [bots.slack.plugins.1.config]
        onlywhispers = false
    [bots.slack.plugins.2]
      type = "giveaway"
      [bots.slack.plugins.2.config]
        mods = ["user1", "user2"]
        onlymods = true
    [bots.slack.plugins.3]
      type = "httpping"
    [bots.slack.plugins.4]
      type = "roll"
    [bots.slack.plugins.5]
      type = "version"
    [bots.slack.plugins.6]
      type = "vote"
      [bots.slack.plugins.6.config]
        mods = ["user1", "user2"]
        onlymods = true
    [bots.slack.plugins.7]
      type = "quotes"
      [bots.slack.plugins.7.config]
        mods = ["user1", "user2"]
        onlymods = true
    [bots.slack.plugins.8]
      type = "timedmessages"
      [bots.slack.plugins.8.config]
        mods = ["user1", "user2"]
        onlymods = true

  [bots.mm]
    type = "mattermost"
    enabled = false
    [bots.mm.storage]
      storage = "memory"
      [bots.mm.storage.config]
        URL = "mongodb://user1:test@localhost/testdb" # URL to connect to
        Database = "testdb" # Database to use
    [bots.mm.config]
			server = "https://server.com"
			username = "username_goes_here"
			password = "password_goes_here"
    [bots.mm.plugins.1]
      type = "echo"
      [bots.mm.plugins.1.config]
        onlywhispers = false
    [bots.mm.plugins.2]
      type = "httpping"
    [bots.mm.plugins.3]
      type = "roll"

  [bots.twitch]
    type = "twitch"
    enabled = true
    [bots.twitch.config]
      username = "username_goes_here"
      token = "token_goes_jere"
      channels = ["channels_to_join", "go_here"]
    [bots.twitch.storage]
      storage = "mongo"
      [bots.twitch.storage.config]
        URL = "mongodb://user1:test@localhost/testdb" # URL to connect to
        Database = "testdb" # Database to use
    [bots.twitch.plugins.1]
      type = "echo"
    [bots.twitch.plugins.1.config]
      onlywhispers = false
    [bots.twitch.plugins.2]
      type = "giveaway"
      [bots.twitch.plugins.2.config]
        mods = ["Someone#5932"]
        onlymods = true
    [bots.twitch.plugins.3]
      type = "httpping"
    [bots.twitch.plugins.4]
      type = "roll"
    [bots.twitch.plugins.5]
      type = "version"
    [bots.twitch.plugins.6]
      type = "vote"
      [bots.twitch.plugins.6.config]
        mods = ["Someone#5932"]
        onlymods = true
    [bots.twitch.plugins.7]
      type = "quotes"
      [bots.twitch.plugins.7.config]
        mods = ["Someone#5932"]
        onlymods = true
    [bots.twitch.plugins.8]
      type = "timedmessages"
      [bots.twitch.plugins.8.config]
        mods = ["Someone#5932"]
        onlymods = true
