#
# Example Bots configuration for the TomlBotsConfigProvider
#

[bots]

  [bots.slack_dev]
    type = "slack"
    enabled = false
    [bots.slack_dev.config]
      workspace = "something"
	    token = "token_goes_here"

    [bots.slack_dev.plugins.1]
      type = "echo"
      [bots.slack_dev.plugins.1.config]
        onlywhispers = false

    [bots.slack_dev.plugins.2]
      type = "giveaway"
      [bots.slack_dev.plugins.2.config]
        mods = ["user1", "user2"]
        onlymods = true

    [bots.slack_dev.plugins.3]
      type = "httpping"

    [bots.slack_dev.plugins.4]
      type = "roll"

    [bots.slack_dev.plugins.5]
      type = "version"

    [bots.slack_dev.plugins.6]
      type = "vote"
      [bots.slack_dev.plugins.6.config]
        mods = ["user1", "user2"]
        onlymods = true

    [bots.slack_dev.plugins.7]
      type = "quotes"
      [bots.slack_dev.plugins.7.config]
        mods = ["user1", "user2"]
        onlymods = true

  [bots.mm_dev]
    type = "mattermost"
    enabled = false
    [bots.mm_dev.config]
			server = "https://server.com"
			username = "username_goes_here"
			password = "password_goes_here"

    [bots.mm_dev.plugins.1]
      type = "echo"
      [bots.mm_dev.plugins.1.config]
        onlywhispers = false

    [bots.mm_dev.plugins.2]
      type = "httpping"

    [bots.mm_dev.plugins.3]
      type = "roll"
