language: go

go:
  - "1.10"

env:
 - GOMAXPROCS=2

install:
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls
    - make deps

script:
    - make
    - make test
    - export GOPATH=$GOPATH:.
    - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
