#
# AbyleBotter example configuration
#

[general]

    enabled = true
    ip = "127.0.0.1"
    port = "8000"

[bots]

  [bots.discord]
  enabled = false
  token = "INSERT_DISCORD_TOKEN_HERE" # can be overwritten via env variable DISCORD_TOKEN

    [bots.discord.plugins.echo]
    enabled = false

    [bots.discord.plugins.giveaway]
    enabled = false

  [bots.fake]
  enabled = true

    [bots.fake.plugins.echo]
    enabled = true

    [bots.fake.plugins.giveaway]
    enabled = false

  [bots.matrix]
  enabled = false
  server = "INSERT_MATRIX_SERVER_HERE" # can be overwritten via env variable MATRIX_SERVER
  username = "INSERT_MATRIX_USER_HERE" # can be overwritten via env variable MATRIX_USERNAME
  password = "INSERT_MATRIX_PASSWORD_HERE" # can be overwritten via env variable MATRIX_PASSWORD
  token = "INSERT_MATRIX_TOKEN_HERE" # can be overwritten via env variable MATRIX_TOKEN

    [bots.matrix.plugins.echo]
    enabled = false

    [bots.matrix.plugins.giveaway]
    enabled = false
