name: Build and Test
on:
  push:
  pull_request:
  
jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Setup go
              uses: actions/setup-go@v2
              with:
                go-version: 1.14

            - name: Run Unit tests.
              run: make test

            - name: Convert coverage to lcov
              uses: jandelgado/gcov2lcov-action@v1.0.0
              with:
                  infile: coverage.out
                  outfile: coverage.lcov

            - name: Coveralls
              uses: coverallsapp/github-action@master
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                path-to-lcov: ./coverage.lcov

    build:
        name: Build
        runs-on: ubuntu-latest 
        needs: [test]
        steps:
            - uses: actions/checkout@v2

            - name: Setup go
              uses: actions/setup-go@v2
              with:
                go-version: 1.14

            - name: Build
              run: make

    build-static:
        name: Build static
        runs-on: ubuntu-latest 
        needs: [test]
        steps:
            - uses: actions/checkout@v2

            - name: Login to docker hub
              if: success()
              uses: actions-hub/docker/login@master
              env:
                DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

            - name: Setup go
              uses: actions/setup-go@v2
              with:
                go-version: 1.14

            - name: Build static
              run: make build-static

            - name: Build image
              if: success()
              run: make build-container-gitcommit

            - name: Push image
              if: success()
              run: make release-container-gitcommit
