name: Build and Test
on:
  push:
  pull_request:
  
jobs:
    test:
    name: Test
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-go@v2
            with:
                go-version: 1.14

        - name: Run Unit tests.
            run: make test
      
    #   - name: Upload Coverage report to CodeCov
    #     uses: codecov/codecov-action@v1.0.0
    #     with:
    #       token: ${{secrets.CODECOV_TOKEN}}
    #       file: ./coverage.txt

  build:
    name: Build
    runs-on: ubuntu-latest 
    needs: [test]
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-go@v2
            with:
                go-version: 1.14

        - name: Build
            run: make build
